export { default as Contacts } from './Contacts/Contacts'
export { default as Footer } from './Footer/Footer'
export { default as Form } from './Form/Form'
export { default as Header } from './Header/Header'
export { default as Nav } from './Nav/Nav'
export { default as Slider } from './Slider/Slider'
export { default as Testimonial } from './Testimonial/Testimonial'
export { default as CAT } from './CAT/CAT'
